version: "2"
services:
    web:
        build: .
        command: python yadageengine
        ports:
            - "25011:25011"
        volumes:
            - ./config:/config
        environment:
            - YADAGE_ENGINE_CONFIG=/config/docker-config.yaml
            - PACKTIVITY_CELERY_REDIS_BROKER=redis://redis
        links:
            - redis
            - db:database
        image: heikomueller/yadage-engine-api
    db:
        image: mongo:3.0.2
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    celery:
        build:
            context: .
            dockerfile: Celery.Dockerfile
        environment:
            - PACKTIVITY_CELERY_REDIS_BROKER=redis://redis
            - C_FORCE_ROOT=true
        command: "/app/run_celery.sh"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - redis
        image: heikomueller/yadage-engine-celery
