properties:
    - key: 'server.apppath'
      value : '/yadage-engine/api/v1'
    - key: 'server.url'
      value : 'http://localhost'
    - key: 'server.port'
      value: 25011
    - key: 'app.name'
      value: 'Yadage Workflow Engine API'
    - key: 'app.doc'
      value: 'http://cds-swg1.cims.nyu.edu/yadage-engine/api/v1/doc/index.html'
    - key: 'app.debug'
      value: true
    - key: 'app.logdir'
      value: './log'
    - key: 'db.workdir'
      value: './data'
    - key:  'mongo.db'
      value: 'yadage'
